import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  heading: {
    fontSize: 40,
    fontWeight: 'bold',
    color: 'orange',
    textAlign: 'center',
    marginVertical: 50,
  },
  itemWrapper: {
    backgroundColor: 'red',
    padding: 20,
    marginVertical: 10,
  },
  itemsName: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  itemsEmail: {
    color: '#f0f0f0',
    fontSize: 16,
  },

  touchableOpacityBtn: {
    backgroundColor: '#8000ff',
    width: '50%',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
    alignSelf: 'center',
    marginBottom: 10,
  },
  touchableHeighlightBtn: {
    backgroundColor: '#ff8000',
    width: '50%',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
    alignSelf: 'center',
  },
  touchableOpacityBtnText: {
    color: '#FFF',
    textAlign: 'center',
    fontSize: 20,
  },
  lodingBox: {
    backgroundColor: '#FFF',
    alignSelf: 'center',
    elevation: 5,
    shadowColor: '#000',
    padding: '30',
    borderRadius: 10,
  },
  inputs: {
    color: '#2d2d2d',
    backgroundColor: '#fff',
    borderColor: '#000',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 10,
    fontSize: 20,
    marginBottom: 10,
  },
  name: {
    color: 'orange',
    fontSize: 22,
    fontWeight: '700',
  },
  email: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '500',
  },
  card: {
    backgroundColor: 'gray',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 10,
    borderLeftWidth: 5,
    borderLeftColor: 'bluebiolet',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f0f0f0',
  },
});
